In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor as RF

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
submission = pd.read_csv('sample_submission.csv')

In [5]:
train[:10]

,Id,Hazard,T1_V1,T1_V2,T1_V3,T1_V4,T1_V5,T1_V6,T1_V7,T1_V8,...,T2_V6,T2_V7,T2_V8,T2_V9,T2_V10,T2_V11,T2_V12,T2_V13,T2_V14,T2_V15
0,1,1,15,3,2,N,B,N,B,B,...,2,37,1,11,6,Y,N,E,2,2
1,2,4,16,14,5,H,B,N,B,B,...,2,22,1,18,5,Y,Y,E,2,1
2,3,1,10,10,5,N,K,N,B,B,...,6,37,2,14,6,Y,Y,E,6,1
3,4,1,18,18,5,N,K,N,B,B,...,2,25,1,1,6,Y,N,C,2,6
4,5,1,13,19,5,N,H,N,B,B,...,1,22,1,2,7,N,N,E,1,1
5,12,1,14,12,2,N,K,N,B,B,...,1,37,1,5,7,N,N,A,1,9
6,15,5,8,17,1,E,K,N,B,B,...,2,25,1,20,3,Y,N,D,2,11
7,19,1,14,20,4,E,K,N,B,B,...,2,40,1,18,7,Y,N,E,3,2
8,21,1,8,2,2,W,C,N,D,B,...,1,34,1,13,5,N,N,A,2,1
9,22,1,5,4,3,B,I,N,D,B,...,4,40,1,6,3,Y,Y,E,4,1

In [6]:
X = train.drop('Hazard', axis = 1)
y = train['Hazard']

In [7]:
num_X = pd.get_dummies(X)
num_Xt = pd.get_dummies(test)

In [15]:
num_X[:10]

,Id,T1_V1,T1_V2,T1_V3,T1_V10,T1_V13,T1_V14,T2_V1,T2_V2,T2_V4,...,T2_V5_F,T2_V11_N,T2_V11_Y,T2_V12_N,T2_V12_Y,T2_V13_A,T2_V13_B,T2_V13_C,T2_V13_D,T2_V13_E
0,1,15,3,2,7,15,1,36,11,10,...,0,0,1,1,0,0,0,0,0,1
1,2,16,14,5,12,10,3,78,10,17,...,0,0,1,0,1,0,0,0,0,1
2,3,10,10,5,12,15,1,71,21,13,...,0,0,1,0,1,0,0,0,0,1
3,4,18,18,5,3,15,1,71,13,15,...,0,0,1,1,0,0,0,1,0,0
4,5,13,19,5,7,10,1,75,10,11,...,0,1,0,1,0,0,0,0,0,1
5,12,14,12,2,12,15,1,65,10,14,...,0,1,0,1,0,1,0,0,0,0
6,15,8,17,1,8,20,1,100,14,16,...,0,0,1,1,0,0,0,0,1,0
7,19,14,20,4,3,15,1,83,13,5,...,0,0,1,1,0,0,0,0,0,1
8,21,8,2,2,8,5,1,20,12,4,...,0,1,0,1,0,1,0,0,0,0
9,22,5,4,3,8,20,3,88,7,14,...,0,0,1,0,1,0,0,0,0,1

In [16]:
model = RF().fit(num_X, y)

In [17]:
prediction = model.predict(num_Xt)

In [18]:
submission['Hazard'] = prediction

In [19]:
submission.to_csv('basic_RF.csv', index = False)